### PR TITLE
Feat: Attack & Defense

### PR DESCRIPTION
**Pull request by XiaoXuxxxx**
@eltfshr will explain this feature.

### CODE REVIEW

**Comment by riflowth** [comment]
Did you test all of **API** endpoints? @eltfshr

**Comment by eltfshr** [comment]
This feat is about battling.
Users can use this feat to capture other clan's planet with their resource

**Comment by XiaoXuxxxx** [comment]
> Did you test all of **API** endpoints? @XiaoXuxxxx

Y.. Y.... Yes!!!

**Comment by riflowth** [comment]
> This feat is about battling.
> Users can use this feat to capture other clan's planet with their resource

Nice. you guys spend a lot of time on this feature.
I have looked into some commits. your code looks nice and clean.

`SO ITTTTT READYYYY TO MERGEEEEEEEEEEE !` 🥇 

Thanks guys
@XiaoXuxxxx 
@eltfshr

**Pull request merged**
